"""Add structured_content to activities

Revision ID: 44b412bf0391
Revises: 994dbb993f24
Create Date: 2026-08-16 01:54:58.807333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b412bf0391'
down_revision: Union[str, Sequence[str], None] = '994dbb993f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('structured_content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'structured_content')
    # ### end Alembic commands ###
