"""Add question_scores to submission

Revision ID: bb1ad4d68c22
Revises: 7e7f341e0065
Create Date: 2026-08-16 02:16:31.840713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1ad4d68c22'
down_revision: Union[str, Sequence[str], None] = '7e7f341e0065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_submissions', sa.Column('question_scores', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_submissions', 'question_scores')
    # ### end Alembic commands ###
