"""Add soft delete to all models

Revision ID: f11c2e251fdf
Revises: efd435ad1c7a
Create Date: 2026-08-15 21:48:41.749414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11c2e251fdf'
down_revision: Union[str, Sequence[str], None] = 'efd435ad1c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('classes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('notifications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'deleted_at')
    op.drop_column('students', 'is_deleted')
    op.drop_column('notifications', 'deleted_at')
    op.drop_column('notifications', 'is_deleted')
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'is_deleted')
    op.drop_column('classes', 'deleted_at')
    op.drop_column('classes', 'is_deleted')
    # ### end Alembic commands ###
